language: node_js
node_js: 10
cache: yarn

before_install:
  - yarn --frozen-lockfile

script:
  - yarn lint
  - yarn stylelint
  - yarn prod

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email: false
